# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-11 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('con_id', models.AutoField(primary_key=True, serialize=False)),
                ('pipingLength', models.FloatField()),
                ('maxFlow', models.FloatField()),
                ('flowDirection', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FlowPoint',
            fields=[
                ('flPoint_id', models.AutoField(primary_key=True, serialize=False)),
                ('function', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('mes_id', models.AutoField(primary_key=True, serialize=False)),
                ('dateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('waterLevel', models.FloatField(default=-1)),
                ('pH', models.FloatField(default=-1)),
                ('conductivity', models.FloatField(default=-1)),
                ('salinity', models.FloatField(default=-1)),
                ('tds', models.FloatField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('pump_id', models.AutoField(primary_key=True, serialize=False)),
                ('maxProdCapacity', models.FloatField()),
                ('maxPumpingCapacity', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('island', models.CharField(max_length=256)),
                ('county', models.CharField(max_length=256)),
                ('town', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PumpConnection',
            fields=[
                ('pump_con_id', models.AutoField(primary_key=True, serialize=False)),
                ('pipingLength', models.FloatField()),
                ('maxFlow', models.FloatField()),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Pump')),
            ],
        ),
        migrations.CreateModel(
            name='Reservoir',
            fields=[
                ('res_id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('island', models.CharField(max_length=256)),
                ('county', models.CharField(max_length=256)),
                ('town', models.CharField(max_length=256)),
                ('heigth', models.FloatField()),
                ('width', models.FloatField()),
                ('length', models.FloatField()),
                ('nrPics', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='pumpconnection',
            name='reservoir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Reservoir'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='reservoir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Reservoir'),
        ),
        migrations.AddField(
            model_name='flowpoint',
            name='reservoir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Reservoir'),
        ),
        migrations.AddField(
            model_name='connection',
            name='reservoirA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='A_con', to='main.Reservoir'),
        ),
        migrations.AddField(
            model_name='connection',
            name='reservoirB',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='B_con', to='main.Reservoir'),
        ),
    ]
