# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-08 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowPoint',
            fields=[
                ('flPoint_id', models.AutoField(primary_key=True, serialize=False)),
                ('function', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('mes_id', models.AutoField(primary_key=True, serialize=False)),
                ('waterLevel', models.FloatField()),
                ('pH', models.FloatField()),
                ('conductivity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservoir',
            fields=[
                ('res_id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('island', models.CharField(max_length=256)),
                ('county', models.CharField(max_length=256)),
                ('town', models.CharField(max_length=256)),
                ('heigth', models.FloatField()),
                ('width', models.FloatField()),
                ('length', models.FloatField()),
                ('pictures', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='measurement',
            name='reservoir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Reservoir'),
        ),
        migrations.AddField(
            model_name='flowpoint',
            name='reservoir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Reservoir'),
        ),
    ]
