# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-09 02:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170708_0501'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
