# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-09 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedPacket',
            fields=[
                ('fp_id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.BinaryField()),
                ('dateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('reservoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Reservoir')),
            ],
        ),
        migrations.AddField(
            model_name='measurement',
            name='dateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
