# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-09 21:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170709_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='failedpacket',
            name='reservoir',
        ),
        migrations.DeleteModel(
            name='FailedPacket',
        ),
    ]
