# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-10 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170709_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservoir',
            name='pictures',
        ),
        migrations.AddField(
            model_name='reservoir',
            name='nrPics',
            field=models.IntegerField(default=0),
        ),
    ]
