# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-11 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170710_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='salinity',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='measurement',
            name='tds',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='conductivity',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='pH',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='waterLevel',
            field=models.FloatField(default=-1),
        ),
    ]
