# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-11 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170711_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conection',
            fields=[
                ('con_id', models.AutoField(primary_key=True, serialize=False)),
                ('pipingLength', models.FloatField()),
                ('maxFlow', models.FloatField()),
                ('reservoirA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='A_con', to='main.Reservoir')),
                ('reservoirB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='B_con', to='main.Reservoir')),
            ],
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('pump_id', models.AutoField(primary_key=True, serialize=False)),
                ('maxProdCapacity', models.FloatField()),
                ('maxPumpingCapacity', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('island', models.CharField(max_length=256)),
                ('county', models.CharField(max_length=256)),
                ('town', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PumpConection',
            fields=[
                ('pump_con_id', models.AutoField(primary_key=True, serialize=False)),
                ('pipingLength', models.FloatField()),
                ('maxFlow', models.FloatField()),
                ('reservoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Reservoir')),
            ],
        ),
    ]
